friends = ["sean" , "joe" , "gomez" , "chester"]
print(friends[0])
print(friends[1].upper())
print(friends[2].title())
print(friends[-1].lower())
message = "Hey, i hope you find someone who makes you believe in love again " + (friends[0].title())
print(message)
message = "I hope you marry that girl, " + (friends[-3].upper())
print(message)
message = "haha you will never bench more than me ever " + (friends[2].title())
print(message)
message = "I hate you and i will never consider you a real friend to me, " + (friends[-1].lower())
print(message)