vacay = ["bora bora" , "hawaii" , "thailand" , "puerto rico" , "tokyo"]
print(vacay)
print(sorted(vacay))
print(vacay)
print(sorted(vacay, reverse=True))
print(vacay)
vacay.reverse()
print(vacay)
vacay.reverse()
print(vacay)
vacay.sort()
print(vacay)
vacay.sort(reverse=True)
print(vacay)